trigger:
  branches:
    include:
      - main  # или любая другая ветка, например 'develop'

pool:
  vmImage: 'ubuntu-latest'  # Использование Ubuntu для сборки, можно выбрать другую платформу

variables:
  buildConfiguration: 'Release'  # Настройка конфигурации сборки (например, 'Release' или 'Debug')

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'  # Укажите версию .NET SDK, которую нужно использовать

- task: Checkout@1  # Проверка исходного кода из репозитория
  inputs:
    clean: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'  # Восстановление зависимостей
    projects: '**/*.csproj'  # Поиск всех .csproj файлов

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'  # Сборка проекта
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'  # Публикация (подготовка артефактов для деплоя)
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop'  # Имя артефакта
    publishLocation: 'Container'  # Место хранения артефактов
