trigger:
  branches:
    include:
      - main  # Или любая другая ветка, например, 'develop'
  paths:
    include:
      - '**/*.docx'  # Отслеживание изменений только в файлах .docx

pool:
  vmImage: 'ubuntu-latest'  # Использование образа Ubuntu для выполнения пайплайна

steps:
  - task: UsePythonVersion@0  # Использование Python для обработки .docx файлов
    inputs:
      versionSpec: '3.x'  # Установка Python 3.x

  - script: |
      python -m pip install --upgrade pip
      pip install python-docx  # Установка библиотеки для работы с .docx файлами
    displayName: 'Install python-docx'

  - script: |
      echo "No .docx files found to process"
    displayName: 'Process .docx files'
