trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  systemDebugContext: 'true'  # Пример определения переменной

steps:
  - task: Checkout@1
    inputs:
      fetchDepth: 1

  - script: |
      echo "System Debug Context: $(systemDebugContext)"
    displayName: 'Check system debug context'

  - script: |
      if [ "$(systemDebugContext)" == "true" ]; then
        echo "Debug context is enabled"
      else
        echo "Debug context is disabled"
      fi
    displayName: 'Conditional step based on variable'
