trigger:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Checkout@1
    inputs:
      fetchDepth: 1  # Это позволяет быстро извлекать последний коммит

  - script: |
      echo "Repository successfully fetched with fetchDepth 1"
    displayName: 'Check repository'
